# Generated by Django 3.2.5 on 2021-07-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('producer', models.CharField(max_length=1024)),
                ('file', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
                ('nationalID', models.CharField(max_length=10)),
                ('wallet', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('introducer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProUser',
            fields=[
                ('prouser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.user')),
                ('expr_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SepecialMovie',
            fields=[
                ('special_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.movie')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=256, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
        ),
    ]
