# Generated by Django 3.2.5 on 2021-07-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210720_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepecialmoviewatch',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.sepecialmovie'),
        ),
    ]
