# Generated by Django 3.2.5 on 2021-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_sepecialmoviewatch_movie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='prouser_id',
            new_name='prouser',
        ),
        migrations.RenameField(
            model_name='movietag',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movietag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='prouser',
            old_name='prouser_id',
            new_name='prouser',
        ),
        migrations.RenameField(
            model_name='sepecialmovie',
            old_name='special_movie_id',
            new_name='special_movie',
        ),
        migrations.RenameField(
            model_name='sepecialmoviewatch',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='sepecialmoviewatch',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
