# Generated by Django 3.2.5 on 2021-07-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210721_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SepecialMovie',
            new_name='SpecialMovie',
        ),
        migrations.RenameModel(
            old_name='SepecialMovieWatch',
            new_name='SpecialMovieWatch',
        ),
    ]
