# Generated by Django 3.2.5 on 2021-07-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210721_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmoviewatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.prouser'),
        ),
    ]
