# Generated by Django 3.2.5 on 2021-07-22 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_specialmoviewatch_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('movie_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.list')),
                ('moive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
