# Generated by Django 3.2.5 on 2021-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='moive',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
